### ISSUE TITLE
global.json部署版本问题

### ISSUE THREAD

**Issue by YukiYlf** [chatop2020/AKStream#1]
我自己的电脑本身是5.0.100
vs2019好像直接是这个版本，我一直以为是3.1的版本
编译要改成5.0.100才可以
否则不行

不过不知道是不是部署到实际系统上面是不是一定是5.0.100的

**Comment by funthing** [comment]
> 我自己的电脑本身是5.0.100
> vs2019好像直接是这个版本，我一直以为是3.1的版本
> 编译要改成5.0.100才可以
> 否则不行
> 
> 不过不知道是不是部署到实际系统上面是不是一定是5.0.100的

这个自己安装.Net Core 3.1也很简单呀，直接搜索下载就行了，3.1是长期维护版本。建议使用3.1开发部署。

**Comment by chatop2020** [comment]
同意@funthing的建议
