### ISSUE TITLE
代码问题太多, 根本运行不起来

### ISSUE THREAD

**Issue by codedever** [chatop2020/AKStream#100]
本项目源代码中问题太多了,  以下是我发现的其中一些
1. WebHookService.cs 第1264 行, 明明判断了 mediaServer 不为空走 if 块, 为空就走 else 块,  接着 1436 行就使用了明知道是空值的 mediaServer, 我不知道别人怎么把项目跑得起来的, 就这样的代码能运行起来才是见了鬼了
![微信图片_20241220214717](https://github.com/user-attachments/assets/f4c46786-dbbb-467c-b576-97e669aef57e)

2. MediaServerService.cs 第5671行对mediaServer 判断了空值, 接下来的代码中并非赋值, 接着5683, 5695行不在判断空值就开始使用了这个可为空的值,  这能不出错吗?
![微信截图_20241220215331](https://github.com/user-attachments/assets/17d195ab-df77-41b4-8fb6-d15520a23524)

类似的大问题挺多的, 就先说这两个

**Comment by chatop2020** [comment]
感谢，发现的bug,不过其实是最近添加的代码，但并未完成，不小心同步上来了，现在改过了，但目前dev,master分支都没有完成，不过一般功能都是正常能用的，跑不起来，自己找找原因
