### ISSUE TITLE
对设备鉴权的一些建议

### ISSUE THREAD

**Issue by mis-czx** [chatop2020/AKStream#11]
增加对单个设备的独立密码,
独立表存放设备ID与密码,设备注册时可以拿着ID取密码进行鉴权

提出该需求的原因
服务器处于公网环境下,设备较多时密码都是统一的,会被别有用心的人进行恶意的攻击,独立密码恰好可以有效的解决

**Comment by chatop2020** [comment]
你指的是sip密码吗？

**Comment by mis-czx** [comment]
是的

**Comment by chatop2020** [comment]
~~这块，我可以在sip配置中加一个选项，这个选项开的时候，统一走数据库密码，关的时候走sip配置中的密码~~

刚才看了一下代码，由于sip网关自治理，本身与数据库无关，这个需求AKStream上没办法做，如果需要的话，你可以自己做一下，也很简单，只要把数据库操作引用进来，当有设备注册时，查一下库，用库里的密码做校验就可以了。

**Comment by chatop2020** [comment]
换了一种方式支持这个需求
Sip网关增加一个设备注册时需要鉴权的事件，当设备注册时向触发此事件，并等待外部事件处理获取设备密钥
如果外部事件处理返回为null或"",则依然使用Sip配置中的密钥，否则则使用外部事件返回的密钥进行鉴权

Sip网关增加

```C#
        /// <summary>
        /// 当设备发生注册鉴权时，需要返回值为此设备的鉴权密钥
        /// </summary>
        public static event GCommon.DeviceAuthentication OnDeviceAuthentication = null!;

```

AKStreamWeb增加对此事件的处理

```C#

         /// <summary>
        /// 当设备注册需要鉴权时，用于获取外部的设备密钥
        /// </summary>
        /// <param name="sipDeviceId"></param>
        /// <returns>返回此设备的密钥</returns>
        public static string OnAuthentication(string sipDeviceId)
        {
            return null;
            //此返回围SipDeviceId所对应的密钥，Sip网关会根据此密钥进行鉴权，返回的是null或“”时，依然使用Sip配置中的密钥鉴权
        }
```

你看这样是不是能满足你的要求
