### ISSUE TITLE
可否新增一个新增流媒体服务器的注册,心跳,离线的回调

### ISSUE THREAD

**Issue by mis-czx** [chatop2020/AKStream#13]
可否新增一个新增流媒体服务器的注册,心跳,离线的回调
类似于设备的上下线心跳注册,
我抛弃了AK的主程序,自己写的,但是发现流媒体无法有效的掌控,

**Comment by chatop2020** [comment]
这个本来就有呀，akstreamkeeper会自动向akstreamweb发送心跳包，akstreamweb就是根据akstreamkeeper的心跳来判别流媒体是正常运行
