### ISSUE TITLE
[BUG]在OnPublish回调里面开启录制失败的问题

### ISSUE THREAD

**Issue by i542873057** [chatop2020/AKStream#15]
![image](https://user-images.githubusercontent.com/16971894/111586145-59ea4b00-87fb-11eb-951e-2283de8e7979.png)

要把EnableMp4改成EnableMP4

**Comment by chatop2020** [comment]
谢谢，我这边改一下
但是总体上，并不建议在这里开始录制，akstream有一个完善的录制计划与自动录制的方案
建议走akstream的录制计划实现录制功能
