### ISSUE TITLE
如何获取历史流进行回放

### ISSUE THREAD

**Issue by yangyuanhang** [chatop2020/AKStream#18]
目前开放的_StreamLive_接口与_LiveVideo_似乎都是获取的实时视频流,请问该怎么获取到指定时间段内的历史流呢

**Comment by chatop2020** [comment]
历史流列表，历史流推流接口都现成做好的
但是流程没有衔接起来，最近没什么时间，暂时没有计划完善这些，你可以自己完成。

**Comment by yangyuanhang** [comment]
> 历史流列表，历史流推流接口都现成做好的
> 但是流程没有衔接起来，最近没什么时间，暂时没有计划完善这些，你可以自己完成。

十分感谢回复,请问下历史流推流是哪个接口呢,swagger文档中没有找到这个接口

**Comment by chatop2020** [comment]
因为流程没有整合起来，所以swagger里也没有，你要看代码

**Comment by chatop2020** [comment]
已经完成了历史录像文件查询与点播功能
