### ISSUE TITLE
配合最新编译的ZLMediaKit时hls无法播放

### ISSUE THREAD

**Issue by pppploi8** [chatop2020/AKStream#20]
经测试，ZLMediaKit的addStreamProxy调用需传递enable_hls=1，不能让json库直接序列化成true，否则会导致ZLMediaKit不生成对应hls流

ZLMediaKit出问题的版本：
编译日期: 2021/03/12-16:10:58
当前git分支: master
当前git hash值: c0f4899950f92b3b1ba4621e55b34f734a029836

**Comment by chatop2020** [comment]
好的，感谢，我改一下

**Comment by chatop2020** [comment]
已修正
