### ISSUE TITLE
这里为什么多次请求的时候有时候是一直返回流地址, 有时候就变成正在推流了

### ISSUE THREAD

**Issue by tonyonce2017** [chatop2020/AKStream#22]
![image](https://user-images.githubusercontent.com/34465929/115210778-81ea0880-a131-11eb-928a-a539f93613a0.png)

**Comment by tonyonce2017** [comment]
提示已经在推流了, 但是请求接口: /MediaServer/GetOnlineStreamInfoList里却查不到正在推流的列表, 然后直接调用ZLM的接口就能查到流列表

**Comment by chatop2020** [comment]
这块，如果你手工streamlive的话，一定要确定二次streamlive的时候，前面已断开，否则就会出现你这个问题。
如果可以用autolive模式的话，建议走autolive吧，因为autolive已经做了很多保障，基本上不会出现这种情况。

**Comment by tonyonce2017** [comment]
> 这块，如果你手工streamlive的话，一定要确定二次streamlive的时候，前面已断开，否则就会出现你这个问题。
> 如果可以用autolive模式的话，建议走autolive吧，因为autolive已经做了很多保障，基本上不会出现这种情况。

请问这个是在哪里配置呢, 是配置通道的autovideo吗

**Comment by chatop2020** [comment]
嗯，通道autolive为true的话，会自动拉流
