### ISSUE TITLE
当ZLMediaKit是使用Docker容器部署时的部署方式

### ISSUE THREAD

**Issue by csuffyy** [chatop2020/AKStream#23]
请教一下，当ZLMediaKit是使用Docker部署的时候，需要怎样部署，AKStream才能正常使用呢？

ZLMediaKit的运行语句是：
docker run -id -p 1935:1935 -p 8080:80 -p 8554:554 -p 10000:10000 -p 10000:10000/udp panjjo/zlmediakit

如果可以的话，建议将AKStream做成一个Docker镜像，支持与ZLMediaKit一起使用docker-compose运行，那样的话使用起来就非常方便了。

非常感谢作者开源了这么好的项目，感谢！

**Comment by 1157457050** [comment]
up

**Comment by chatop2020** [comment]
已经有网友维护了docker版本
https://github.com/scottzhang/AKStreamDocker
可以尝试一下。
