### ISSUE TITLE
GetSipDeviceList 无返回信息

### ISSUE THREAD

**Issue by lb240** [chatop2020/AKStream#30]
日志收到了 Sip设备注册信息（无错误日志） ，但是videochannel没有信息，接口也返回空是为啥？

**Comment by chatop2020** [comment]
如果sip设备列表日志都打出来了的话，说明是正常的
sip设备第一次被发现时，会自动进入数据库，但是这个时候是未激活状态
你可以使用/MediaServer/GetWaitForActiveVideoChannelList接口获取未激活的通道，然后通过
​/MediaServer​/ActiveVideoChannel接口来激活通道

**Comment by lb240** [comment]
日志如下：
2021-05-11 14:42:08,509 [siptrans-recv] DEBUG AKStream - [SipServer]->收到来自udp:192.168.1.100:5060的Sip设备注册信息->REGISTER sip:34020000002000000001@3402000000 SIP/2.0
Via: SIP/2.0/UDP 192.168.1.100:5060;rport=5060;branch=z9hG4bK408744088;received=192.168.1.100
To: <sip:34020000001110000001@3402000000>
From: <sip:34020000001110000001@3402000000>;tag=944803989
Call-ID: 527661143
CSeq: 228 REGISTER
Contact: <sip:34020000001110000001@192.168.1.100:5060>
Max-Forwards: 70
User-Agent: Embedded Net DVR/NVR/DVS
Expires: 86400
Content-Length: 0


但是：
数据库表 videochannels 无数据
接口返回无数据：
{"videoChannelList":[],"request":{"pageIndex":1,"pageSize":10,"orderBy":[{"fieldName":"id","orderByDir":"ASC"}]},"total":0}

**Comment by lb240** [comment]
日志如下：
2021-05-11 14:42:08,509 [siptrans-recv] DEBUG AKStream - [SipServer]->收到来自udp:192.168.1.100:5060的Sip设备注册信息->REGISTER sip:34020000002000000001@3402000000 SIP/2.0
Via: SIP/2.0/UDP 192.168.1.100:5060;rport=5060;branch=z9hG4bK408744088;received=192.168.1.100
To: <sip:34020000001110000001@3402000000>
From: <sip:34020000001110000001@3402000000>;tag=944803989
Call-ID: 527661143
CSeq: 228 REGISTER
Contact: <sip:34020000001110000001@192.168.1.100:5060>
Max-Forwards: 70
User-Agent: Embedded Net DVR/NVR/DVS
Expires: 86400
Content-Length: 0


但是：
数据库表 videochannels 无数据
接口返回无数据：
{"videoChannelList":[],"request":{"pageIndex":1,"pageSize":10,"orderBy":[{"fieldName":"id","orderByDir":"ASC"}]},"total":0}
