### ISSUE TITLE
请求直播流/SipGate/LiveVideo出现接口错误

### ISSUE THREAD

**Issue by tonyonce2017** [chatop2020/AKStream#33]
![image](https://user-images.githubusercontent.com/34465929/121623472-54bb3600-caa2-11eb-8324-a0345d78069c.png)
报这个错, AKStream和ZLM均为最新版本

**Comment by chatop2020** [comment]
这个你要debug一下，原因可能很多
这是使用很频繁的接口，我这里在用的没有这个问题。
