### ISSUE TITLE
自动拉流

### ISSUE THREAD

**Issue by tonyonce2017** [chatop2020/AKStream#34]
![image](https://user-images.githubusercontent.com/34465929/124347044-c5bebb00-dc14-11eb-84d2-46ee8c3fe6b4.png)
大佬好, 我走国标协议, 这里设置的autovideo为true, 是不是直接在VLC里播放流地址就会自动可以了, 不过我测试没法直接播放, 我还需要做什么设置吗

我手动激活通道请求流地址时拿到的流地址可以播放, 自动的不行

**Comment by chatop2020** [comment]
建议你多看看wiki,国标流程很长的，要配置要激活要推流，播放地址也不在数据库上
另外，可以加群问问别人，群号在项目主页上。
