### ISSUE TITLE
如何让摄像头推回放流

### ISSUE THREAD

**Issue by youngking0727** [chatop2020/AKStream#35]
你好，因为我使用的摄像头是带本地存储的，我想通过时间戳只让摄像头将自身的某一段时间回放流推送给流媒体，该怎么实现呢？谢谢！

**Comment by youngking0727** [comment]
我的akstream部署在云上，无法在摄像头本地部署

**Comment by chatop2020** [comment]
使用gb28181接入摄像头，可以通过sip信令查询摄像头的录像文件，然后通过点播录像文件就可以实现你说的推回放流，具体回qq群问吧，群里有人做用。
