### ISSUE TITLE
摄像头采用H265编码，会报错；回放和直播播放十几秒后也报错。

### ISSUE THREAD

**Issue by helloCZZ** [chatop2020/AKStream#37]
当编码为H265时报：some flv fles video error "MediaError: CodecUnsupported Flv: Unsupported codec in video frame: 12"
改为H264后能播放，但十几秒后会出现     MediaError:MediaMSEError

**Comment by chatop2020** [comment]
看你是什么方式，如果使用selfmethod模式拉的流，那只支持h264/acc,如果使用ffmpeg拉的流，支持h264,h265/acc/g711
建议进QQ群和大家交流吧。
