### ISSUE TITLE
把AKStream部署到docker容器时, 外部无法访问到5800端口

### ISSUE THREAD

**Issue by tonyonce2017** [chatop2020/AKStream#39]
将AKStream部署到docker容器, 容器使用ubuntu18.04, 将5800映射到宿主机, 发现无法连接到映射的端口, 但是能从外部ping通该端口, 进入容器, 查看日志, 无任何报错, 然后在容器内部执行curl 127.0.0.1:5800, 发现同样无法访问, 使用netstat -plt查看端口情况跟, 5800只出现在tcp6, 对比发现, SIP端口5060会同时出现在tcp和tcp6, sip服务外部访问正常

相同的部署方式, 部署在非docker容器, curl操作可以正常返回数据

**Comment by chatop2020** [comment]
这是你docker的配置问题
