### ISSUE TITLE
级联时下级平台新增设备或设备状态变更上级无法感知

### ISSUE THREAD

**Issue by yangyuanhang** [chatop2020/AKStream#49]
问题描述:
下级新增设备并设置共享上级无法接收到新设备
下级设备掉线时上级设备状态仍是在线感知不到下级设备状态变化

请问有计划完善吗或者可以提供下解决思路吗 对级联不太熟悉

**Comment by chatop2020** [comment]
AKStream这块已经提供了足够多的级联演示，因为级联并不是我自己的需求目标，在功能完善更新方面会有所滞后，你可以自己完善一下代码，能提供PR的话，那就更好了。
