### ISSUE TITLE
摄像头本地录像回放功能有计划吗？

### ISSUE THREAD

**Issue by 818ajian** [chatop2020/AKStream#5]
chatop2020
您好！用4G摄像头，录像需要存储在本地，所以需要基于国标的摄像头本地录像回放功能，不知道这个功能什么时候能实现?感谢您的辛苦付出！

**Comment by chatop2020** [comment]
AKStream支持基于gb28181的远程录制文件列表获取，远程录制文件回放流请求功能（现在回放流请求接口没开放），但我总体上认为，这并不是一个好方案
对于4G的摄像机来讲，我更加建议在4G摄像机本地组建一个局域网，将AKStream前置到这个局域网内，这样摄像机的音视频流可以通过此局域网获取流数据，而不会产生4G通信流量费用
AKStream内部有完善的录制计划，可以将这些流进行实时录制，将录制权交由AKStream要优于将录制权放在摄像机上。
AKStream将这些流集中起来以后，可以通过nat123,frp等内网穿透方案来实现对流，对录制文件的远程按需点播。
