### ISSUE TITLE
已注册的设备信息变更后，数据库内容没有更新

### ISSUE THREAD

**Issue by windsfan** [chatop2020/AKStream#50]
AKStreamWeb/Misc/SipServerCallBack.cs 代码中
     sipChannel.SipChannelStatus != DevStatus.OFF) //只有视频设备并且是可用状态的进数据库
            {
                var obj = ORMHelper.Db.Select<VideoChannel>().Where(x =>
                    x.ChannelId.Equals(sipChannel.DeviceId) && x.DeviceId.Equals(sipChannel.ParentId) &&
                    x.DeviceStreamType.Equals(DeviceStreamType.GB28181)).First();
                if (obj != null)
                {
                    return;
                }
如果设备已经存在了则直接返回，导致如果前端的设备信息发生变生化数据库中没有更新。
建议优化逻辑，增加update数据库逻辑更新设备的基础信息（如ChannelName、IpV4Address、IpV6Address）信息，实现设备信息与数据库信息的同步

**Comment by chatop2020** [comment]
这块，确实有不完善的地方，你可以提供PR吗？

**Comment by windsfan** [comment]
不会.net。我是发现这个现像，看代码逻辑发现这个问题的。应该加上这个数据处理是比较容易的
