### ISSUE TITLE
录制计划

### ISSUE THREAD

**Issue by Small-North** [chatop2020/AKStream#53]
AKStream录制计划是跟视频通道绑定的，视频通道就是往一个地址拉流，然后这个视频通道绑定这个录制计划，按照录制计划进行录制。推流的好像不支持，推流录制的只能走MediaServer的Web Hook的OnPublish（流发布事件），里面再调用开始录制接口。
我的理解对吗？

**Comment by chatop2020** [comment]
AKStream逻辑上没有支持直播流，所以也不会对直播流进行录制，如果需要对直播流进行录制，要在AKStream里增加直播流兼容的逻辑，这一整套都要自己二次开发
