### ISSUE TITLE
获取设备目录失败

### ISSUE THREAD

**Issue by tonyonce2017** [chatop2020/AKStream#54]
抓报文, 摄像头注册和心跳都正常发, 向摄像头获取设备目录时, 设备立即返回200 OK, 但是始终没见返回设备目录
![image](https://user-images.githubusercontent.com/34465929/192401790-d5fb0479-78bf-47f1-a3da-a8498604a691.png)

**Comment by chatop2020** [comment]
国标协议各厂商实现的都不完整，现在所知，宇视平台国标协议做的就很奇怪，需要你根据对方国标协议对AKStream进行改造，才能完全 兼容。
