### ISSUE TITLE
大华的国标 注册不上来

### ISSUE THREAD

**Issue by itchangc** [chatop2020/AKStream#58]
![~99` 27FQ({IWOY7`Z{5(_Q](https://user-images.githubusercontent.com/40175292/210058679-9948d36f-7547-48fe-91b8-09ae15919edd.jpg)
![7M0D`4Y$N0BUPFH@%AZ2918](https://user-images.githubusercontent.com/40175292/210058697-263155ff-f20f-4480-92d4-6001264529f6.jpg)

设备请求注册，服务端查询目录，此时设备返回 403了
![4FX@K2@}5$7`L6592J%$0M](https://user-images.githubusercontent.com/40175292/210058729-812f14dd-c8e1-42d9-8f79-f025170170b1.jpg)

海康，宇视没有问题，就是大华注册的时候出现这个问题

**Comment by itchangc** [comment]
这是我抓取的sip注册的数据包 ，下载地址如下：  
https://itcc.lanzoul.com/iDLqx0jq7wrc

**Comment by itchangc** [comment]
问题解决了：大华的设备 识别不了 tryingResponse  这个请求，需要把这个请求做下处理。

**Comment by jiechengyang** [comment]
> 问题解决了：大华的设备 识别不了 tryingResponse 这个请求，需要把这个请求做下处理。

您好，哥们，是不是判断如果是大华的注册信息，则`SIPResponse tryingResponse = SIPResponse.GetResponse(sipRequest, SIPResponseStatusCodesEnum.Trying, null);` 就不发生呢，可否贴下你的处理

**Comment by jiechengyang** [comment]
> 大华的设备 识别不了 tryingResponse 这个请求，需要把这个请求做下处理。

sip中的100trying到底有啥用
SIP是一种类似HTTP的基于请求响应的协议。理想情况下，请求被发出后，应该无任何延迟的传回响应。但是这是理想情况，有些时候接收端收到请求后进行处理需要一定的延迟，这个延迟是不一定的，SIP中有一个超时机制，超过某个时延会重发请求。为防止这种处理请求的延迟造成消息重发，接收端在收到请求后会立即发送一个临时的响应，1XX都是临时的，告诉发送端我已收到，正在处理，让发送端的计时器停止，不需要重新发送请求了。

**Comment by itchangc** [comment]
> > 问题解决了：大华的设备 识别不了 tryingResponse 这个请求，需要把这个请求做下处理。
> 
> 您好，哥们，是不是判断如果是大华的注册信息，则`SIPResponse tryingResponse = SIPResponse.GetResponse(sipRequest, SIPResponseStatusCodesEnum.Trying, null);` 就不发生呢，可否贴下你的处理

可以这样做，我是直接删除了

**Comment by jiechengyang** [comment]
@itchangc 感谢

**Comment by xsir99** [comment]
> > > 问题解决了：大华的设备 识别不了 tryingResponse 这个请求，需要把这个请求做下处理。
> > 
> > 
> > 您好，哥们，是不是判断如果是大华的注册信息，则`SIPResponse tryingResponse = SIPResponse.GetResponse(sipRequest, SIPResponseStatusCodesEnum.Trying, null);` 就不发生呢，可否贴下你的处理
> 
> 可以这样做，我是直接删除了

@itchangc  老哥， 能不能贴一下删除了那一行代码， c# 完全不会..
