### ISSUE TITLE
录像回放的进度拖拽，不管是否成功都返回成功

### ISSUE THREAD

**Issue by ShuiFan0** [chatop2020/AKStream#59]
AKStreamWeb\Services\SipServerService.cs
1715行的值没有被返回

改成下面这样应该就没问题了
`
            bool liveVideoRet;
            try
            {
                SipMethodProxy sipMethodProxy = new SipMethodProxy(Common.AkStreamWebConfig.WaitSipRequestTimeOutMSec);
                liveVideoRet = sipMethodProxy.InviteRecordPosition(record, pushMediaInfo, time, out rs);
            }
            catch (Exception ex)
            {
                return false;
            }

            var taskWait = new WebHookNeedReturnTask(Common.WebHookNeedReturnTask);
            AutoResetEvent myWait = new AutoResetEvent(false);
            taskWait.AutoResetEvent = myWait;
            Common.WebHookNeedReturnTask.TryAdd($"WAITONPUBLISH_{record.Stream}",
                taskWait);

            var isTimeout = myWait.WaitOne(Common.AkStreamWebConfig.WaitEventTimeOutMSec);

            ReqForWebHookOnPublish onPublishWebhook = (ReqForWebHookOnPublish)taskWait.OtherObj;
            Common.WebHookNeedReturnTask.TryRemove($"WAITONPUBLISH_{videoChannel.MainId}",
                out WebHookNeedReturnTask task);
            if (task != null)
            {
                task.Dispose();
            }

            GCommon.Logger.Debug(
                $"[{Common.LoggerHead}]->拖拽Sip回放流成功->{record.SipDevice.DeviceId}-{record.SipChannel.DeviceId}-{record.Stream}");

            return liveVideoRet;
`

**Comment by chatop2020** [comment]
你说的对，已修复 。
