### ISSUE TITLE
linux系统命令路径问题

### ISSUE THREAD

**Issue by bjhuitou** [chatop2020/AKStream#6]
我用的是ubuntu系统，/usr/sbin/route和/usr/sbin/ifconfig是不存在的，而是/sbin/route和/sbin/ifconfig，如果可以根据系统区分下就更好了。

**Comment by YukiYlf** [comment]
我和你遇到了同样的问题
编译不了
我改了 代码路径

**Comment by YukiYlf** [comment]
我改了代码里面的路径 /sbin/route和/sbin/ifconfig
但是运行时候没反应，没错误，没任何提示

**Comment by YukiYlf** [comment]
我的运行程序 都在挂在盘上面，而且我是用sqlite数据库，准备弄穿透

**Comment by chatop2020** [comment]
如果各别操作系统的系统工具路径不一致，建议自己做一下软连接
```shell
ln -s 目标路径 软连接路径
```
如，上面所说的ubuntu系统，可以做如下操作，当然必须在root用户下才可以

```shell
ln -s /sbin/route /usr/sbin/route
ln -s /sbin/ifconfig /usr/sbin/ifconfig
```
这样就可以解决你的问题
