### ISSUE TITLE
为了增加稳定性，建议对各种意外情况增加Bye包

### ISSUE THREAD

**Issue by ShuiFan0** [chatop2020/AKStream#71]
类`AKStreamWeb.Services.SipServerService`

函数`        public static MediaServerStreamInfo LiveVideo(int taskId, string ssrcId, out ResponseStruct rs,
            ushort? rtpPort = 0)`
“请求Sip推回放流成功(此回放流本身就处于推流状态)”这个if包外的后面，增加
```
new SipMethodProxy(Common.AkStreamWebConfig.WaitSipRequestTimeOutMSec).DeInvite(record, out _);//停止推流（重新拉流的时候，无条件要求服务端停止推流）
```
`if (!isTimeout)`包里面，增加
```
new SipMethodProxy(Common.AkStreamWebConfig.WaitSipRequestTimeOutMSec).DeInvite(record, out rs);//停止推流（超时的时候，无条件要求服务端停止推流）
```

同理，
函数`        public static MediaServerStreamInfo LiveVideo(string deviceId, string channelId, out ResponseStruct rs,
            ushort? rtpPort = 0)`
“请求Sip推流成功(此Sip通道本身就处于推流状态)”这个if包外的后面，增加
```
new SipMethodProxy(Common.AkStreamWebConfig.WaitSipRequestTimeOutMSec).DeInvite(sipChannel, out _);//停止推流（重新拉流的时候，无条件要求服务端停止推流）
```
`if (!isTimeout)`包里面（sipChannel属性赋值的后面），增加
```
new SipMethodProxy(Common.AkStreamWebConfig.WaitSipRequestTimeOutMSec).DeInvite(sipChannel, out rs);//停止推流（超时的时候，无条件要求服务端停止推流）
```

**Comment by chatop2020** [comment]
这个操作通过closestreams方法在该做的地方都做了
