### ISSUE TITLE
某些基于GB2312编码的系统可能带来'?'字符，然后本程序将其转成'\0'造成异常

### ISSUE THREAD

**Issue by ShuiFan0** [chatop2020/AKStream#72]
相关类：
```
LibCommon.Structs.GB28181.XML.Catalog
```

引起错误的调用`value == null ? "" : value.Replace();`

期望：不报错
我直接把它改成了`value ?? string.Empty;`
现在都是通过参数化读写数据库的，没必要在这里过滤

**Comment by chatop2020** [comment]
这块是标准库过来的类，可能标准库是为了更好的兼容性吧，实际没需要的话，直接改掉就可以了。
