### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ghost** [chatop2020/AKStream#74]
AKStreamWeb: 
ERROR AKStream - [AKStreamWeb]->HTTP-OUTPUT->127.0.0.1->GET->/MediaServer/ListRtpServer->StatusCode:400->Body: {"Code":"MediaServer_InstanceIsNull","Message":"流媒体服务实例为空，请先创建流媒体服务实例"}

AKStreamKeeper:
WARN  AKStream - [AKStreamKeeper]->流媒体服务器还未就绪,无法提供RtpServer列表,下次循环继续尝试...
WARN  AKStream - [AKStreamKeeper]->获取Rtp端口列表异常->{"Code":"MediaServer_ObjectNotExists","Message":"指定对象不存在"}

数据库可以建表但无内容:[
![屏幕截图 2023-11-05 105523](https://github.com/chatop2020/AKStream/assets/118689842/f1c98c0e-919e-437a-b55c-9e247ac234c4)

配置与上个版本一样但无法运行, ip地址经过修改依然报错, 应该不是这个问题, sip服务可以正常收到设备的注册.

**Comment by chatop2020** [comment]
没有发现这个问题，估计是你配置的问题吧。

LovElizabeth ***@***.***> 于2023年11月5日周日 11:52写道：
