### ISSUE TITLE
_guessAnRtpPort

### ISSUE THREAD

**Issue by zhlei101201** [chatop2020/AKStream#79]
89行
                   if (minPort > maxPort)
                   {
                       var tmp = minPort;
                       maxPort = minPort;
                       minPort = tmp;
                   }
这里看起来是要交换，但是minPort并没有改变

**Comment by chatop2020** [comment]
这是端口序列保证从小到大的控制，是担心配置文件填写时的失误而导致的异常情况出现，所以这里做了这个保障
如果小端口大于大端口，说明配置文件里写错了，比如     5000-4900，这种情况时，实际应该写成4900-5000,所以需要在真正处理的时候，把这个方向颠倒过来。

至于为什么会有这么无用的逻辑写在里面，，，那肯定是曾经出现过这样无脑的配置。
