### ISSUE TITLE
其他协议是否支持转国标

### ISSUE THREAD

**Issue by kyle-cao** [chatop2020/AKStream#8]
您好 感谢您的开源分享
请问一下 目前是否支持RTMP、RTSP转国标 ？
国标是否支持上下级级联？

**Comment by chatop2020** [comment]
1.rtsp,rtmp,http等协议格式暂时不支持转国标，不过这块功能可能在后续支持起来
2.暂时也不支持作为下级平台级联上级平台，后续也可能支持起来
主要原因是，我自己暂时还用不到这些功能

**Comment by kyle-cao** [comment]
好的 期待中
