### ISSUE TITLE
请教关于VideoOnlineInfo与MediaServer数据同步的问题

### ISSUE THREAD

**Issue by zhlei101201** [chatop2020/AKStream#80]
（AutoTaskOther.cs）代码中，通过多次（TimesToDelete）比对MediaServer缺少相应的在线流数据，才删除本地的ldb缓存数据
为何要多次比对，难道zlm的数据不准确吗？

**Comment by chatop2020** [comment]
因为mediaserver与akstream本身没有实时数据通讯通道，所以两边的数据可能会有一定的延迟，因此为了做到一定准确，所以增加了这个保障机制，而保障机制的存在，事实上并不会对业务产生大的影响。
