### ISSUE TITLE
编译部署安装 AKStreamWeb的5800与AKStreamKeeper的6880端口无法访问

### ISSUE THREAD

**Issue by dengwoadeng** [chatop2020/AKStream#82]
编译部署安装的程序 AKStreamWeb的5800与AKStreamKeeper的6880端口都无法访问,服务器防火墙全都端口都已放行 
其余端口:5060  tcping 可以
![image](https://github.com/chatop2020/AKStream/assets/34929719/18227308-eedd-4bcc-9848-bf94dd1f1952)

**Comment by chatop2020** [comment]
看监听ip是不是127.0.0.1

**Comment by dengwoadeng** [comment]
ListenIp 的值 不管改成 0.0.0.0 还是"" 都是一样的问题 无法访问
![image](https://github.com/chatop2020/AKStream/assets/34929719/f64837b7-3af9-41d6-b4a7-e1e1976aa48a)
执行r日志
![image](https://github.com/chatop2020/AKStream/assets/34929719/34d53b32-6128-4f0b-9d76-8833b3ddc010)

**Comment by peter0591** [comment]
问题解决了吗？我也出现一样的问题
