### ISSUE TITLE
等待流媒体服务器回调响应超时

### ISSUE THREAD

**Issue by xuofeng** [chatop2020/AKStream#83]
zlm正常启动着
![image](https://github.com/chatop2020/AKStream/assets/16606684/31d1859a-7b6d-4343-b88c-f6d2262b863f)
![image](https://github.com/chatop2020/AKStream/assets/16606684/d646cfe4-777f-4a1d-a87c-70da4f383231)

**Comment by chatop2020** [comment]
不知道你想问的问题是什么

**Comment by xuofeng** [comment]
> 不知道你想问的问题是什么

![image](https://github.com/chatop2020/AKStream/assets/16606684/03fdd0ac-1225-4ecd-9cf6-e5b37347a290)
zim提示超时 请问是什么原因导致的，设备状态都是在线的
![image](https://github.com/chatop2020/AKStream/assets/16606684/e7a2ae6b-c55e-4561-ac50-f8fc56047465)

**Comment by chatop2020** [comment]
这应该是前后端配合问题，推流断开，就是断开了，前端应该没有及时修改状态

**Comment by ls10097714** [comment]
> > 不知道你想问的问题是什么
> 
> ![image](https://private-user-images.githubusercontent.com/16606684/320368353-03fdd0ac-1225-4ecd-9cf6-e5b37347a290.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNTA0MjIsIm5iZiI6MTcyNjA1MDEyMiwicGF0aCI6Ii8xNjYwNjY4NC8zMjAzNjgzNTMtMDNmZGQwYWMtMTIyNS00ZWNkLTljZjYtZTViMzczNDdhMjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDEwMjIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxZjFjNzViM2I4OTA3OWY5YzEzOTRmZjk2YWYyMmU5NTZhZGY4MGU3NTQzZGMwNGVhYzhkZjU1ZTkyMjA0NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qkeW7nil61T_JmZbHsvxBGJ-PnoqTjrIZfcaX0kpVdM) zim提示超时 请问是什么原因导致的，设备状态都是在线的 ![image](https://private-user-images.githubusercontent.com/16606684/320368506-e7a2ae6b-c55e-4561-ac50-f8fc56047465.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNTA0MjIsIm5iZiI6MTcyNjA1MDEyMiwicGF0aCI6Ii8xNjYwNjY4NC8zMjAzNjg1MDYtZTdhMmFlNmItYzU1ZS00NTYxLWFjNTAtZjhmYzU2MDQ3NDY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDEwMjIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YTdhYjhjOGNmNzVmN2IzM2QyNmYxYmU1ZDg4OWYxOWJiOTE5NDE4YTRmYzZkYjFiMjI0ODhjZDQ1NzIwMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pFnD3zoYsL_CaAtn_eNTtEDXBpkxDFp7gXuUt_Z9cX4)
![image](https://github.com/user-attachments/assets/1f794aa6-8209-4ec1-ba69-7f0b2050d2cd)

我也遇到了同样的问题，我前端使用AKStreamNVR，让开相机画面就提示超时

**Comment by lxw136** [comment]
你好 解决了吗
