### ISSUE TITLE
Use this repo to do this job?

### ISSUE THREAD

**Issue by zydjohnHotmail** [chatop2020/AKStream#84]
你好，
我有一个问题要问：我可以使用你的 REPO 完成这项工作吗？
当我下载一个M3U8流时，我只需要下载音频部分，并将下载的音频部分合并成小文件wav格式（频率为16KHZ），这样我就可以使用一些语音库将语音转换为文本(实时)。
如果可能，请向我展示一些说明和代码示例。
谢谢!

**Comment by chatop2020** [comment]
This job is not akstream's domain of expertise and can be done using whisper
