### ISSUE TITLE
按照教程配置启动，大华配置GB28181后，未查询到通道信息

### ISSUE THREAD

**Issue by Myosotissylvatica36** [chatop2020/AKStream#85]
问题：大华摄像头配置了 GB28181后，在页面上看到了有设备注册过来，但是未自动添加进设备管理，通道也是空的，请问我该如何进行排查
![Up![SIPServer配置](https://github.com/chatop2020/AKStream/assets/41574632/a662fd29-5837-4c59-9ebc-d588000df4b2)
![SIPClient配置](https://github.com/chatop2020/AKStream/assets/41574632/9570831a-bcd1-46e5-973f-21cdbe7d4f2b)

![摄像头配置](https://github.com/chatop2020/AKStream/assets/41574632/c5facdb4-0650-402e-8cc7-8b2365718d6a)

![设备列表](https://github.com/chatop2020/AKStream/assets/41574632/86df91bc-532a-4211-a457-3f61f147829b)

![无通道](https://github.com/chatop2020/AKStream/assets/41574632/bd42d185-e4f6-4d89-a1b5-c5eaeabb08d1)

**Comment by Myosotissylvatica36** [comment]
也是获取设备目录失败导致

**Comment by peter0591** [comment]
这个问题最后如何解决的？
