### ISSUE TITLE
一直报错SIP设备不存在，自动推流失败

### ISSUE THREAD

**Issue by RuoLv** [chatop2020/AKStream#91]
![image](https://github.com/user-attachments/assets/11c711b4-ccfa-4840-8429-1e7436061b37)
![image](https://github.com/user-attachments/assets/528dceff-fb41-4535-91e8-b27365d26986)

**Comment by chatop2020** [comment]
这个你查一下，在推流的时候，设备是不是真的在线呀。
我觉得可能性比较大的是心跳周期太长了造成akstream把设备踢掉了，心跳周期在SipServer的配置文件里可以调整

**Comment by RuoLv** [comment]
> 这个你查一下，在推流的时候，设备是不是真的在线呀。 我觉得可能性比较大的是心跳周期太长了造成akstream把设备踢掉了，心跳周期在SipServer的配置文件里可以调整

不会，这俩设备接在同一个交换机中没有额外的网络环境，用的是海康威视的摄像头直接本地有线连接。 收到的信息都是完整的，就是没有设备，很奇怪
