### ISSUE TITLE
流媒体服务器还未就绪,无法提供RtpServer列表；获取Rtp端口列表异常->{"Code":"MediaServer_ObjectNotExists","Message":"指定对象不存在"}

### ISSUE THREAD

**Issue by asddsaqwejlkj** [chatop2020/AKStream#97]
在配置完毕然后启动项目的时候就报错JSON反序列化异常，然后似乎无法将流媒体服务示例注册进去
![question1](https://github.com/user-attachments/assets/43b41044-95ee-440a-b314-380d9f306a95)
![question2](https://github.com/user-attachments/assets/0173a0cf-20c1-4290-aded-4d3cc5203c52)

**Comment by rx-x-x** [comment]
您好，请问该问题是否有解决，遇到同样的问题想问一下怎么解决的，错误是什么

**Comment by HeChenz** [comment]
这种情况可能需要检查一下数据库服务是否在akstreamweb之前启动
